[build]
  command = "npm run build"
  publish = "dist" # Adjust this if your output directory is different

[[plugins]]
  package = "netlify-plugin-node-version"
  version = "14.19.0" # Use a version that suits your project