[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "*"
  to = "index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-node-version"
  inputs = { version = "14.19.0" }